# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DictMsg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DictMsg.proto',
  package='test_protoc',
  serialized_pb=_b('\n\rDictMsg.proto\x12\x0btest_protoc\"e\n\x07\x44ictMsg\x12\x0c\n\x04name\x18\x01 \x01(\x05\x12&\n\x03msg\x18\x02 \x01(\x0b\x32\x19.test_protoc.DictMsg.Json\x1a$\n\x04Json\x12\x0e\n\x06status\x18\x01 \x02(\x05\x12\x0c\n\x04\x64\x65sc\x18\x02 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DICTMSG_JSON = _descriptor.Descriptor(
  name='Json',
  full_name='test_protoc.DictMsg.Json',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='test_protoc.DictMsg.Json.status', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='desc', full_name='test_protoc.DictMsg.Json.desc', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=131,
)

_DICTMSG = _descriptor.Descriptor(
  name='DictMsg',
  full_name='test_protoc.DictMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='test_protoc.DictMsg.name', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg', full_name='test_protoc.DictMsg.msg', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DICTMSG_JSON, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=131,
)

_DICTMSG_JSON.containing_type = _DICTMSG
_DICTMSG.fields_by_name['msg'].message_type = _DICTMSG_JSON
DESCRIPTOR.message_types_by_name['DictMsg'] = _DICTMSG

DictMsg = _reflection.GeneratedProtocolMessageType('DictMsg', (_message.Message,), dict(

  Json = _reflection.GeneratedProtocolMessageType('Json', (_message.Message,), dict(
    DESCRIPTOR = _DICTMSG_JSON,
    __module__ = 'DictMsg_pb2'
    # @@protoc_insertion_point(class_scope:test_protoc.DictMsg.Json)
    ))
  ,
  DESCRIPTOR = _DICTMSG,
  __module__ = 'DictMsg_pb2'
  # @@protoc_insertion_point(class_scope:test_protoc.DictMsg)
  ))
_sym_db.RegisterMessage(DictMsg)
_sym_db.RegisterMessage(DictMsg.Json)


# @@protoc_insertion_point(module_scope)
