# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DistMsg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DistMsg.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\rDistMsg.proto\"\x8d\x01\n\x07\x44istMsg\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0e\n\x06status\x18\x02 \x01(\x05\x12&\n\x08\x63ontacts\x18\x03 \x03(\x0b\x32\x14.DistMsg.PhoneNumber\x1a<\n\x0bPhoneNumber\x12\x0e\n\x06mobile\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DISTMSG_PHONENUMBER = _descriptor.Descriptor(
  name='PhoneNumber',
  full_name='DistMsg.PhoneNumber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mobile', full_name='DistMsg.PhoneNumber.mobile', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='DistMsg.PhoneNumber.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address', full_name='DistMsg.PhoneNumber.address', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=159,
)

_DISTMSG = _descriptor.Descriptor(
  name='DistMsg',
  full_name='DistMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='DistMsg.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='DistMsg.status', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='contacts', full_name='DistMsg.contacts', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DISTMSG_PHONENUMBER, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=159,
)

_DISTMSG_PHONENUMBER.containing_type = _DISTMSG
_DISTMSG.fields_by_name['contacts'].message_type = _DISTMSG_PHONENUMBER
DESCRIPTOR.message_types_by_name['DistMsg'] = _DISTMSG

DistMsg = _reflection.GeneratedProtocolMessageType('DistMsg', (_message.Message,), dict(

  PhoneNumber = _reflection.GeneratedProtocolMessageType('PhoneNumber', (_message.Message,), dict(
    DESCRIPTOR = _DISTMSG_PHONENUMBER,
    __module__ = 'DistMsg_pb2'
    # @@protoc_insertion_point(class_scope:DistMsg.PhoneNumber)
    ))
  ,
  DESCRIPTOR = _DISTMSG,
  __module__ = 'DistMsg_pb2'
  # @@protoc_insertion_point(class_scope:DistMsg)
  ))
_sym_db.RegisterMessage(DistMsg)
_sym_db.RegisterMessage(DistMsg.PhoneNumber)


# @@protoc_insertion_point(module_scope)
